#%RAML 1.0 Library
uses:
  annotations: ../../annotations/annotationsLibrary.raml
  customControlAttributes: ../customControlAttributes.raml

types:
  auditableData:
    type: customControlAttributes.customControlAttributes
    discriminatorValue: AUDITABLE_DATA
    description: |
      To mark certain attributes so that its information is shown in plain text for the input/output, but internally obfuscated in audit logs.
    properties:
      geographies:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PUT"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "DELETE"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: array
        description: List of geographies for the behaviour.
        minItems: 1
        uniqueItems: true
        items:
          type: object
          description: A behaviour from this geography.
          properties:
            id:
              (annotations.bindingDefinition):
                - method: "GET"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "POST"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PUT"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PATCH"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "DELETE"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
              type: string
              description: Geography (specified with the ISO 3166-1 alfa-2 two letters code or GLOBAL value).
              pattern: ^(GLOBAL|[A-Z]{2})$
              example: ES
            omitted:
              (annotations.bindingDefinition):
                - method: "GET"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "POST"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PUT"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PATCH"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "DELETE"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
              type: boolean
              description: When value is true, the data is omitted. The default value is false.
  maskAndUnmask:
    type: customControlAttributes.customControlAttributes
    description: |
      To ensure that a customer operates with the mask identifiers that correspond to their contracts (combination of the identifier of that resource and that of the contract customer).
    discriminatorValue: MASK_AND_UNMASK
    properties:
      geographies:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PUT"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "DELETE"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: array
        description: List of geographies for the behaviour.
        minItems: 1
        uniqueItems: true
        items:
          type: object
          description: A behaviour from this geography.
          properties:
            id:
              (annotations.bindingDefinition):
                - method: "GET"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "POST"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PUT"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PATCH"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "DELETE"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
              type: string
              description: Geography (specified with the ISO 3166-1 alfa-2 two letters code or GLOBAL value).
              pattern: ^(GLOBAL|[A-Z]{2})$
              example: ES
            customerMask?:
              (annotations.bindingDefinition):
                - method: "GET"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "POST"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PUT"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PATCH"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "DELETE"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
              type: string
              description: Replace with the start and end positions (beginning at 0) of the client identifier within the operation identifier separated by a "-", for example, 6-10. In this example, if the value of the operation identifier were 123456AB5788ER, the customer corresponds to AB578.
              example: "4-6"
            contractMask?:
              (annotations.bindingDefinition):
                - method: "GET"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "POST"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PUT"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PATCH"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "DELETE"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
              type: string
              description: Replace with the start and end positions (beginning at 0) of the contract identifier within the operation identifier separated by a "-", for example, 4-8. In this example, if the value of the operation identifier were 123456AB5788ER, the contract corresponds to 56AB5.
              example: "4-6"
  encryptionAndDecryption:
    type: customControlAttributes.customControlAttributes
    discriminatorValue: ENCRYPTION_AND_DECRYPTION
    description: |
      Allows an attribute to be internally to be encrypted and decrypted (as appropriate) so that the information arrives at the message recipient in the appropriate form (encrypted or decrypted), allowing them to operate without worrying about whether it was sent under encryption or if it has to be decrypted.
    properties:
      geographies:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PUT"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "DELETE"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: array
        description: List of geographies for the behaviour.
        minItems: 1
        uniqueItems: true
        items:
          type: object
          description: A behaviour from this geography.
          properties:
            id:
              (annotations.bindingDefinition):
                - method: "GET"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "POST"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PUT"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PATCH"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "DELETE"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
              type: string
              description: Geography (specified with the ISO 3166-1 alfa-2 two letters code or GLOBAL value).
              pattern: ^(GLOBAL|[A-Z]{2})$
              example: ES
            inFunction:
              (annotations.bindingDefinition):
                - method: "GET"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "POST"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PUT"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PATCH"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "DELETE"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
              type: string
              description: String identifier of the security function to be applied to the data during input, so that it arrives at the service with the function applied (e.g., "decypher").
              example: "decypher"
            outFunction:
              (annotations.bindingDefinition):
                - method: "GET"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "POST"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PUT"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "PATCH"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
                - method: "DELETE"
                  input: "OPTIONAL"
                  output: "OPTIONAL"
              type: string
              description: String identifier of the security function to be applied to the data during output, so that it arrives at the person invoking the service with the function applied (e.g., "cypher").
              example: "cypher"
