#%RAML 1.0
title: petShop
description: Pet Shop Api
version: 0.0
baseUri: http://localhost:8081/petshop/v0

uses:
  petshops:  types/petshops.raml

resourceTypes: 
  collection: !include glapi-global-apis-commons-commons/resourceTypes/collection.raml

/petshops:
  description: |
    petshops in the town
  type: collection
  get:
    description: |
      petshops lists
    queryParameters:
      petshops.id:
        description: |
          petshops id
        type: number
        required: true
        example: 1
      petshops.address:
        description: |
          petshops address
        type: string
        required: true
        example: "Insurgentes Sur 345, Hipódromo, 06170, CDMX"
      petshops.contact:
        description: |
          petshops contact
        type: number
        required: true
        example: 55674309
      petshops.schedule:
        description: |
          petshops schedule
        type: string
        required: true
        example: "Lunes a Domingo de 9:00am a 8:00pm"
      petshops.logo:
        description: |
          petshops logo
        type: string
        required: true
        example: "logo.jpg"
    responses:
      200:
        body:
          application/json:
            example: !include examples/get_200.json

/services:
  description: |
    services collection resource used to create new services
  type: collection
  get:
    is: [ assets.paging ]
    description: |
      lists all services of a specific user
    queryParameters:
      services.id:
        description: |
          services id
        type: number
        required: true
        example: 1964401a
      services.pet:
        description: |
          services pet
        enum:
          - dog 
          - cat 
          - fish 
          - rodent
          - bird
        required: true
        example: [dog, cat, fish, rodent, bird]
    responses:
      200:
        body:
          application/json:
            type: assets.services
            examples:
              single-order:
                services:
                  -
                    order_id: "ORDER-437563756"
                    creation_date: "2016-03-30"
                    items:
                      -
                        product_id: "PRODUCT-1"
                        quantity: 5
                      -
                        product_id: "PRODUCT-2"
                        quantity: 2
              multiple-services:
                  services:
                    -
                      order_id: "ORDER-437563756"
                      creation_date: "2016-03-30"
                      items:
                        -
                          product_id: "PRODUCT-1"
                          quantity: 5
                        -
                          product_id: "PRODUCT-2"
                          quantity: 2
                    -
                      order_id: "ORDER-437542111"
                      creation_date: "2016-03-30"
                      items:
                        -
                          product_id: "PRODUCT-7"
                          quantity: 6
