#%RAML 1.0
title: petshop
description: Pet Shop Api
version: 0.0
baseUri: http://localhost:8081/petshop/v0

uses:
  date: !include types/date.raml
  pagination: !include glapi-global-apis-commons-commons/types/pagination.raml

resourceTypes: 
  collection: !include glapi-global-apis-commons-commons/resourceTypes/collection.raml
  collection-item: !include glapi-global-apis-commons-commons/resourceTypes/collection-item.raml

traits: 
  pageable: !include glapi-global-apis-commons-commons/traits/pageable.raml

/dates:
  description: Used for interact with information about dates
  type: collection
  get:
    is: [pageable]
    description: Get information about my dates
    queryParameters: 
      date.price:
        description: |
          price of dates
        type: number
        required: true
        example: 100
      date.service_id:
        description: |
          depend of my service id
        type: number
        required: true
        example: 1
      date.petshop_id:
        description: |
          depend of petshop id
        type: number
        required: true
        example: 100
      date.client_id:
        description: |
          depend of client id
        type: number
        required: true
        example: 100
    responses: 
      200:
        description: Ok: Successful response, get dates
        body:
          application/json:
            type: date[]
            example: !include examples/dates/get_200.json
  post:
    description: Create a new date
    body:
      type: date
      application/json:
        example: !include examples/dates/post_200.json
    responses: 
      200:
        description: Ok: Successful created
        body:
          application/json:
            example: |
              { 
                "status": 200, 
                "message": "Successful created!" 
              }
  /{date-id}:
    description: Detail of date from id
    type: collection-item
    get:
      description: Get information about date, from {date-id}
      uriParameters:
        date-id:
          type: number
          description: ID unique for my date
          example: 1
      responses:
        200:
          description: Ok: Successful response, get dates
          body:
            application/json:
              type: date[]
              example: !include examples/dates/date_id/get_200.json 
    put:
      description: Update all information for one register of date from {date-id}
      uriParameters:
        date-id:
          type: number
          description: ID unique for my date
          example: 1
      body:
        type: date
        application/json:
          example: !include examples/dates/date_id/put_200.json
      responses: 
        200:
          description: Ok: Successful response, update information (All)
          body:
            application/json:
              example: |
                { 
                  "status": 200, 
                  "message": "Successful updated! (All)" 
                }
      patch:
        description: Update partial information for one register of date from {date-id}
        uriParameters:
          date-id:
            type: number
            description: ID unique for my date
            example: 1
        body:
          type: date
          application/json:
            example: !include examples/dates/date_id/patch_200.json
        responses: 
          200:
            description: Ok: Successful response, update information (partial)
            body:
              application/json:
                example: |
                  { 
                    "status": 200, 
                    "message": "Successful updated! (Partial)" 
                  }
      delete:
        description: Delete information about date, from {date-id}
        uriParameters:
          date-id:
            type: number
            description: ID unique for my date
            example: 1
        responses:
          200:
            description: Ok: Successful response, delete date
            body:
              application/json:
              type: date[]
              example: !include examples/dates/date_id/get_200.json 




