#%RAML 1.0 Library

uses:
  annotations: ../annotations/annotationsLibrary.raml

types:
  customControlAttributes:
    type: object
    discriminator: kind
    properties:
      kind:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PUT"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
          - method: "DELETE"
            input: "OPTIONAL"
            output: "OPTIONAL"
        required: true
        type: string
        enum: [CUSTOMER_ACCESS_CONTROL, CONTRACT_ACCESS_CONTROL, USER_CHANNEL_CONTROL, CONTRACT_CHANNEL_CONTROL,
          AMOUNT_CHANNEL_CONTROL, AUDITABLE_DATA, MASK_AND_UNMASK, ENCRYPTION_AND_DECRYPTION]
        description: Kind of the validation.
        (annotations.enumDescription):
          - CUSTOMER_ACCESS_CONTROL: Ensure that the specified customer can only access the resources to which he has permissions.
          - CONTRACT_ACCESS_CONTROL: Ensure that the specified customer can only access the contracts to which he has permissions.
          - USER_CHANNEL_CONTROL: To customize the visualization, operative, limits, permissions, etc. that user will have about the resource based on the channel he is using.
          - CONTRACT_CHANNEL_CONTROL: To customize the visualization, operative, limits, permissions, etc. of the contracts that a customer will have on the resource based on the channel he is using.
          - AMOUNT_CHANNEL_CONTROL: To customize the limits, permissions, etc. of the amounts of the contracts that a customer will have on the resource based on the channel he is using.
          - AUDITABLE_DATA: To mark certain attributes so that its information is shown in plain text for the input/output, but internally obfuscated in audit logs.
          - MASK_AND_UNMASK: To ensure that a customer operates with the mask identifiers that correspond to their contracts (combination of the identifier of that resource and that of the contract customer).
          - ENCRYPTION_AND_DECRYPTION: Allows an attribute to be internally to be encrypted and decrypted (as appropriate) so that the information arrives at the message recipient in the appropriate form (encrypted or decrypted), allowing them to operate without worrying about whether it was sent under encryption or if it has to be decrypted.
