#%RAML 1.0 DataType

description: Default data structure for errors in BBVA Ether APIs (ECS)
type: object
properties:
  _error:
    type: object
    description: This object is mandatory for any controlled errors.
    required: true
    properties:
      code:
        type: string
        required: true
        description: Service level error. It will be mandatory to consign discipline name prior to error code in order to avoid name colliding.
      message:
        type: string
        required: true
        description: Human readable error it will always be on English and you MUST not use it for translation, use the _error.code instead.
      extendedInfo:
        type: string
        required: false
        description: Blob information to debug purposes.
