#%RAML 1.0 DataType
description: Array structure based on RFC-6902 - JavaScript Object Notation (JSON) Patch
type: array
items:
  properties:
    op:
      type: string
      required: true
      description: Defines the operation to apply
      enum: ["add", "remove", "replace", "move", "copy", "test"]
    path:
      type: string
      required: true
      description: In all operations, defines the path where operation is applied
    from:
      type: string
      required: false
      description: In copy or move operations, defines the origin of the operation
    value:
      type: string
      required: false
      description: In add, replace and test operations, defines the new value of the operation
