#%RAML 1.0
types:
Accesories:
  type:object
  description: Entity that represent the list of Accesories
  properties:
    id:
      type: number
      description: identify of the Accesories
      required: false
    type:
      type: string
      description: Accesories type
      required: false
    color:
      type: string
      description: identify of the Accesories
      required: true
    material:
      type: string
      description: identify of the Accesories
      required: true
    brand:
      type: string
      description: identify of the brand
      required: true