#%RAML 1.0
types:
  accesory:
    type: object
    description: Accessory of a pet store.
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Accessory Identifier
        required: false
      type:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Accesories type
        required: false
      color:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Accessory color
        required: true
      material:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Material from which the accessory is made
        required: true
      brand:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Accessory brand
        required: true