#%RAML 1.0
types:
  accessories:
    type: array
    description: List of accessories from a pet store
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "POST"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Identifier of a list of accessories
        required: true
      type:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Type of accessories
        required:false
      color:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Accessories color
        required: false
      material:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Accessories Material
        required: false
      brand:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: Accessories brand
        required: false