#%RAML 1.0
types:
  accessories:
    type:array
    description: Entity that represent accessories
    items:
      properties:
        id:
          type: number
          description: identify of the Accesories
          required: true
        type:
          type: string
          description: Accesory type
          required: true
        color:
          type: string
          description: Accesory color
          required: true
        material:
          type: string
          description: Accesory material
          required: true
        brand:
          type: string
          description: Accesory brand
          required: true