#%RAML 1.0
types:
Accesory:
  type:object
  description: Entity that represent the Accesory
  properties:
    id:
      type: number
      description: identify of the Accesories
      required: false
    type:
      type: string
      description: Accesories type
      required: false
    color:
      type: string
      description: identify of the Accesory
      required: true
    material:
      type: string
      description: identify of the material Accesory
      required: true
    brand:
      type: string
      description: identify of the brand of the Accesory
      required: true