#%RAML 1.0
uses:
  annotations : ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  address:
    type: object
    description: Entity that represent an address
    properties:
      address-id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: identifier for each address register
        required: false
      city:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: city from the address
        required: false
      mayoralty:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: number
        description: number of street
        required: false
      colony:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: petShop schedule
        required: false
      street:
		(annotations.bindingDefinition):
          - methoQd: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: petShop logo
        required: false
      no-int:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: petShop name
        required: false
      no-ext:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: petShop name
        required: false
      postal-code:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: petShop name
        required: false
