#%RAML 1.0
types:
  animal:
    type:object
    description: Entity that represent an animal
    properties:
      id:
        type: number
        description: identify of the animal
        required: true
      type:
        type: union
        description: animal type
        required:true
      age:
        type: number
        description: animal age
        required: true
      weight:
        type: number
        description: identify the animal weight
        required: false
      size:
        type: enum
        description: identify the animal size
        required: true
      color:
        type: string
        description: identify the animal color
        required: false