#%RAML 1.0
types:
  animal:
    type:array
    description: Entity that represent an animal
    items:
      properties:
        id:
          type: string
          description: identify of the animal
          required: false
        specie:
          type: enum
          description: animal specie
          required: false
        age:
          type: string
          description: animal age
          required: false
        weight:
          type: number
          description: animal's weight
          required: false
        size:
          type: enum
          description: animal's size
          required: false
        color:
          type: string
          description: animal color
          required: false
        type:
          type: enum
          description: animal type
          required: false