#%RAML 1.0
#%RAML 1.0 Library
uses:
  annotations : ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml
types:
  animal:
    type:object
    description: Entity that represent an animal
    properties:
      id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
		      - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: identify of the animal
        required: false
      specie:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
		      - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
		      - method: "PUT"
            input: "OPTIONAL"
            output: "OPTIONAL"
		      - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: enum
        description: animal specie
        required: false
      age:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: animal age
        required: false
      weight:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
		      - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: animal's weight
        required: false
      size:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: enum
        description: animal's size
        required: false
      color:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		      - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: animal color
        required: false
      type:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
		      - method: "POST"
            input: "OPTIONAL"
            output: "OPTIONAL"
		      - method: "PUT"
            input: "OPTIONAL"
            output: "OPTIONAL"
		      - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: enum
        description: animal type
        required: false