#%RAML 1.0
types:
	birds:
		type:array
		description: Entity that represent a birds
		properties:
			id:
				type: number
				description: identify of the birds
				required: false
			animal_type:
				type: string
				description: identify the birds type
				required: false
    
      
    