#%RAML 1.0
types:
	bird:
		type:object
		description: Entity that represent a bird
		properties:
			id:
				type: number
				description: identify of the bird
				required: false
			animal_type:
				type: string
				description: identify the bird type
				required: false
    
      
    