#%RAML 1.0
types:
	cat:
		type:object
		description: Entity that represent a cat
		properties:
			id:
				type: number
				description: identify of the cat
				required: false
			animal_type:
				type: string
				description: identify the cat type
				required: false
    
      
    