#%RAML 1.0
types:
	cats:
		type:array
		description: Entity that represent a cats
		properties:
			id:
				type: number
				description: identify of the cats
				required: false
			animal_type:
				type: string
				description: identify the cats type
				required: false
    
      
    