#%RAML 1.0
types:
  client:
    type:object
    description: Entity that represent an Client
    properties:
      id:
        type: number
        description: identify of the Client
        required: false
      name:
        type: string
        description: identify the name of the client
        required: false
      age:
        type: number
        description: identify age of the client
        required: false
      pet:
        type: string
        description: identify of the Client
        required: false
      contact:
        type: number
        description: identify of the contact number
        required: false