#%RAML 1.0
types:
  dates:
    type: object
    description: Entity that represent a date
    items:
      properties:
        id:
          type: number
          description: identify of the date
          required: false
        schedule:
          type: string
          description: identify the schedule of the date
          required: false
        description:
          type: string
          description: describe the Dates
          required: false
        price:
          type: number
          description: just price
        service_id:
          type: number
          description: service_id
          required: false
        petshop_id:
          type: number
          description: petshop_id
          required: false
        client_id:
          type: number
          description: client_id
          required: false