#%RAML 1.0
types:
	dog:
		type:object
		description: Entity that represent a dog
		properties:
			id:
				type: number
				description: identify of the dog
				required: false
			animal_type:
				type: string
				description: identify the dog type
				required: false
    
      
    