#%RAML 1.0
types:
	dogs:
		type:array
		description: Entity that represent a dogs
		properties:
			id:
				type: number
				description: identify of the dogs
				required: false
			animal_type:
				type: string
				description: identify the dogs type
				required: false
    
      
    