#%RAML 1.0
types:
  employee:
    type: array
    description: Entity that represent an Employee
    properties:
      id:
        type: number
        description: identify of the Employee
        required: false
      name:
        type: string
        description: identify the name of the Employee
        required: false
      age:
        type: number
        description: identify age of the Employee
        required: false
      position:
        type: string
        description: identify the position of the Employee
        required: false
      contact:
        type: number
        description: identify of the contact number
        required: false