#%RAML 1.0
types:
	fishes:
		type:array
		description: Entity that represent a fishes
		properties:
			id:
				type: number
				description: identify of the fishes
				required: false
			animal_type:
				type: string
				description: identify the fishes type
				required: false
    
      
    