#%RAML 1.0
types:
	fish:
		type:object
		description: Entity that represent a fish
		properties:
			id:
				type: number
				description: identify of the fish
				required: false
			animal_type:
				type: string
				description: identify the fish type
				required: false
    
      
    