#%RAML 1.0
types:
  food:
    type: object
    description: Entity that represent a Food
    properties:
      id:
        type: number
        description: identify of the Food
        required: false
      pet:
        type: string
        description: identify the pets that can eat Food
        required: false
      brand:
        type: string
        description: identify the brand of Food 
        required: false
      presentation:
        type: string
        description: describes the presentation of the Food
        required: false
      
    