#%RAML 1.0
types:
  petShop:
    type: object
    description: Entity that represent a petShop
    properties:
      id:
        type: number
        description: identify of the petShop
        required: true
      address:
        type: string
        description: petShop address
        required: true
      contact:
        type: number
        description: petShop contact
        required: true
      schedule:
        type: string
        description: petShop schedule
        required: true
      logo:
        type: string
        description: petShop logo
        required: true
    
      
    