#%RAML 1.0
types:
  petshop:
    type: object
    description: Entity that represent a petShop
    properties:
      id:
        type: string
        description: identify of the petShop
        required: false
      city:
        type: string
        description: petShop city
        required: false
      contact:
        type: number
        description: petShop contact
        required: false
      horary:
        type: string
        description: petShop horary
        required: false
      name:
        type: string
        description: petShop name
        required: false
    
      
    