#%RAML 1.0
types:
  petshop:
    type: array
    description: Entity that represent a petShops
    properties:
      id:
        type: string
        description: identify of the petShops
        required: false
      city:
        type: string
        description: petShops city
        required: false
      contact:
        type: number
        description: petShops contact
        required: false
      horary:
        type: string
        description: petShops horary
        required: false
      name:
        type: string
        description: petShops name
        required: false
    
      
    