#%RAML 1.0
types:
  petshop:
    type: array
    description: Entity that represent a petShops
    properties:
      id:
        type: number
        description: identify of the petShops
        required: true
      address:
        type: string
        description: petShops address
        required: true
      contact:
        type: number
        description: petShops contact
        required: true
      schedule:
        type: string
        description: petShops schedule
        required: true
      logo:
        type: string
        description: petShops logo
        required: true
    
      
    