#%RAML 1.0
uses:
  annotations : ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  phone-number:
    type: object
    description: Entity that represent a petShop
    properties:
      phone-number-id:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
		  - method: "POST"
            input: "NONE"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		 - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: number
        description: identify of the petShop
        required: false
      full-number:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		 - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: string
        description: petShop address
        required: false
      extension:
		(annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "OPTIONAL"
		  - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
		  - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
		 - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: number
        description: petShop contact
        required: false
		(annotations.bindingDefinition):
