#%RAML 1.0
types:
	rodents:
		type:array
		description: Entity that represent a rodents
		properties:
			id:
				type: number
				description: identify of the rodents
				required: false
			animal_type:
				type: string
				description: identify the rodents type
				required: false
    
      
    