#%RAML 1.0
types:
	rodent:
		type:object
		description: Entity that represent a rodent
		properties:
			id:
				type: number
				description: identify of the rodent
				required: false
			animal_type:
				type: string
				description: identify the rodent type
				required: false
    
      
    