#%RAML 1.0
#%RAML 1.0 Library
uses:
  annotations : ../../glapi-global-apis-commons-commons/annotations/annotationsLibrary.raml

types:
  schedules:
    type: array
    description: Entity that represent a schedules
    properties:
      schedules-id:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "NONE"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: identify of the schedules
        required: false
      day:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: number
        description: day of schedules
        required: false
      month:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: month of schedules
        required: false
			year:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "OPTIONAL"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "OPTIONAL"
            output: "OPTIONAL"
        type: number
        description: year of schedules
        required: false
			time:
        (annotations.bindingDefinition):
          - method: "GET"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "POST"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PUT"
            input: "REQUIRED"
            output: "REQUIRED"
          - method: "PATCH"
            input: "REQUIRED"
            output: "REQUIRED"
        type: string
        description: time of schedules
        required: false