#%RAML 1.0
types:
  service:
    type: object
    description: Entity that represent a service
    properties:
      id:
        type: number
        description: identify of the service
        required: true
      type:
        type: enum
        description: type of service
        required: true
      petshop-id:
        type: number
        description: petshop that provides the service
        required: true