#%RAML 1.0
types:
  services:
    type: array
    description: Entity that represent a services
    items:
      properties:
        id:
          type: number
          description: identify of the services
          required: true
        type:
          type: enum
          description: type of service
          required: true
        petshop-id:
          type: number
          description: petshop that provides the service
          required: true
    
      
    