#%RAML 1.0 AnnotationTypeDeclaration
uses:
  accessControl: ../types/customControl/access.raml
  channelControl: ../types/customControl/channel.raml
  securityControl: ../types/customControl/security.raml

displayName: customControlAttributes
description:  |
  Annotation to add specific control actions on the attributes (uri parameters, query parameters or input/output body properties) of an API.
allowedTargets: [TypeDeclaration]
type: array
items: accessControl.customer | accessControl.contract
  | channelControl.user | channelControl.contract | channelControl.amount
  | securityControl.auditableData | securityControl.maskAndUnmask | securityControl.encryptionAndDecryption
