#%RAML 1.0 Trait
queryParameters:
  fields:
    description: The fields you want to be returned. It can be used with any request that returns response data.
    type: string
    required: false
    example: <<example>>
