#%RAML 1.0 Trait
queryParameters:
  unmasked:
    description: "It indicates that the operation to try to perform around the entity <<resourcePathName | !singularize>> needs to return the unmasked values."
    type: boolean
    required: false
    default: false
    example: true
