#%RAML 1.0 Trait
queryParameters:
  views:
    type: string
    required: false
    example: <<example>>
    description: |
      Retrieves the selected view of each element in the result list.
      Possible values for this parameter are: <<viewsList>>
